# -*- coding: utf-8 -*-
"""CowsayOutput.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Upb-rtVVxPs19Ll_YctJKQgVJYTe8yOp
"""

pip install cowsay

import cowsay
cowsay.daemon("Hi Daemon")